import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Add, Cup, Heart, Message, People, Save2, Share } from "iconsax-react";
import { toast } from "sonner";
import { useAuth } from "@/auth/auth-context";
import { PermissionGate } from "@/auth/permission-gate";
import { employeeApi } from "@/api/services";
import { queryKeys } from "@/lib/query-keys";
import { titleCase } from "@/lib/utils";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState, ErrorState, PageLoader } from "@/components/ui/states";

export function ExploreScreen() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const posts = useQuery({ queryKey: queryKeys.explore(user?.organizationId), queryFn: () => employeeApi.posts(user!.organizationId), enabled: Boolean(user) });
  const challenges = useQuery({ queryKey: ["explore", user?.organizationId, "challenges"], queryFn: () => employeeApi.challenges(user!.organizationId), enabled: Boolean(user) });
  const like = useMutation({ mutationFn: (postId: string) => employeeApi.likePost(user!.organizationId, postId), onMutate: async (postId) => { await queryClient.cancelQueries({ queryKey: queryKeys.explore(user?.organizationId) }); const previous = queryClient.getQueryData(queryKeys.explore(user?.organizationId)); queryClient.setQueryData(queryKeys.explore(user?.organizationId), (items: typeof posts.data) => items?.map((item) => item.id === postId ? { ...item, likeCount: item.likeCount + 1 } : item)); return { previous }; }, onError: (_error, _id, context) => { queryClient.setQueryData(queryKeys.explore(user?.organizationId), context?.previous); toast.error("Like wasn’t saved."); }, onSettled: () => queryClient.invalidateQueries({ queryKey: queryKeys.explore(user?.organizationId) }) });
  return <div><PageHeader title="Explore" /><div className="page-pad grid gap-7"><section className="story-rail"><button className="story add-story"><span><Add color="currentColor" size="22" /></span><small>Your story</small></button>{["Energy crew", "Mindful work", "Friday wins", "New joiners"].map((label, index) => <button className="story" key={label}><span><img src={`/assets/figma/${index % 2 ? "mood-excited.png" : "mood-happy.png"}`} alt="" /></span><small>{label}</small></button>)}</section><section><div className="section-heading"><div><span className="eyebrow">Grow together</span><h2>Challenges</h2></div><PermissionGate permission="challenges.create"><Button size="sm"><Add color="currentColor" size="18" /> Create</Button></PermissionGate></div><div className="challenge-rail">{(challenges.data ?? []).slice(0, 3).map((challenge) => <Card className="explore-challenge" key={challenge.id}><Cup color="currentColor" size="23" variant="TwoTone" /><strong>{challenge.title}</strong><div className="mini-progress"><span style={{ width: `${challenge.progress ?? 0}%` }} /></div><small>{challenge.progress ?? 0}% complete</small></Card>)}</div></section><section><div className="section-heading"><div><span className="eyebrow">From your community</span><h2>Latest posts</h2></div></div>{posts.isLoading ? <PageLoader /> : posts.isError ? <ErrorState retry={() => void posts.refetch()} /> : posts.data?.length ? <div className="post-feed">{posts.data.map((post) => <Card className="post-card" key={post.id}><div className="post-author"><span className="avatar small">{post.authorId.slice(0, 2).toUpperCase()}</span><div><strong>Wellstaq colleague</strong><small>{new Date(post.createdAt).toLocaleDateString()}</small></div></div>{post.content && <p>{post.content}</p>}{post.mediaUrl && <img className="post-media" src={post.mediaUrl} alt="Post attachment" />}<div className="post-actions"><button onClick={() => like.mutate(post.id)}><Heart color="currentColor" size="20" /> {post.likeCount}</button><button><Message color="currentColor" size="20" /> {post.commentCount}</button><button><Share color="currentColor" size="20" /> {post.shareCount}</button><button aria-label="Save post"><Save2 color="currentColor" size="20" /></button></div></Card>)}</div> : <EmptyState title="Your community is warming up" body="Posts, stories and club updates will appear here." />}</section><section className="action-list"><h2>Find your people</h2><button className="action-row"><span><People color="currentColor" size="21" /></span><span><strong>Clubs</strong><small>{titleCase("meet_people_with_shared_interests")}</small></span></button></section></div></div>;
}
